version: '3.8'

services:
  enterprise_ai_studio:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: enterprise_ai_studio_app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - enterprise-ai-network

  # Optional: Add a reverse proxy for production deployment
  nginx-proxy:
    image: nginx:alpine
    container_name: enterprise_ai_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
    depends_on:
      - enterprise_ai_studio
    restart: unless-stopped
    networks:
      - enterprise_ai_network
    profiles:
      - production

networks:
  enterprise_ai_network:
    driver: bridge

volumes:
  nginx-logs: